project:
  type: website
website:
  title: "Test project"
  navbar:
    left:
      - file: "Main/About.qmd"
      - sidebar:reports
  sidebar:
    - id: reports
      title: "Reports"
      contents: "Reports"